### ISSUE TITLE
about the acc

### ISSUE THREAD

**Issue by morning4346** [Kurumi233/Mutual-Channel-Loss#2]
I see you change the acc about vgg16 ,66.06,
我很奇怪的是，前几天我用你的代码确实跑到了66.7，今天再用你的代码只跑到65.93(还没跑完)，我很奇怪，你改了啥

**Comment by Kurumi233** [comment]
> I see you change the acc about vgg16 ,66.06,
> 我很奇怪的是，前几天我用你的代码确实跑到了66.7，今天再用你的代码只跑到65.93(还没跑完)，我很奇怪，你改了啥

pytorch的随机初始似乎会有影响，多跑几遍结果会有不同，比如alpha1.5的时候，最开始只有61的acc。
所以加入了random_seed，以及vgg里面加了参数初始化（仿照torchvision）。
